language: node_js
node_js:
  - v9.11.2
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiters_tests

before_script:
  - psql -c 'create database waiters_tests' -U postgres
  - psql -U postgres -d waiters_tests -a -f table.sql
